# Generated by Django 3.0.6 on 2020-05-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='display_name',
            field=models.CharField(default='testuser', max_length=50),
        ),
    ]
